name: tm-fall-2024
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas
  - pip
  - xarray
  - ipywidgets
  - python-awips
  - scikit-learn
  - seaborn
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    # See: https://github.com/ecmwf-lab/ai-models-graphcast?tab=readme-ov-file#installation
    - ai-models-graphcast
    - jax[cuda12_pip]
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
