name: tm-fall-2024
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.11'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas
  - pip
  - xarray
  - ipywidgets
  - python-awips
  - scikit-learn
  - seaborn
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - git+https://github.com/NVIDIA/earth2mip
    - torch
    - torchvision
    - torchaudio
    - --extra-index-url https://download.pytorch.org/whl/cu121
