name: metpy-hytest-2024
channels:
  - conda-forge
dependencies:
  - cartopy
  - dataretrieval
  - dask
  - geopandas
  - jupyterlab
  - matplotlib
  - metpy
  - nc-time-axis
  - netcdf4
  - numpy
  - pandas<2  # siphon NCSS endian-ness fun
  - pykdtree
  - pythia-datasets
  - s3fs
  - seaborn
  - siphon
  - xarray<2023.03
  - zarr
