name: unidata-cpu
channels:
  - conda-forge
dependencies:
  - act-atmos
  - arm_pyart
  - cartopy
  - cf_xarray
  - dask
  - geopandas
  - intake
  - intake-esm
  - intake-xarray
  - ipympl
  - jupyter
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pint
  - pint-xarray
  - pip
  - pykdtree
  - pyproj
  - python
  - python==3.10
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - siphon
  - tensorflow-cpu
  - tqdm
  - xarray
  - xgboost
  - pip:
    - palmerpenguins
    - rich
    - jupyterlab_myst
    - wget
