name: fit24f
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - tensorflow  
  - statsmodels  
  - seaborn  
  - scipy  
  - arm_pyart  
  - netcdf4  
  - keras  
  - gdal  
  - geotiff  
  - geoviews  
  - geopandas
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - palmerpenguins
