#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil expand-links:t f:t inline:t num:t p:nil pri:nil prop:nil
#+options: stat:t tags:t tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+options: auto-id:t
#+options: H:6

#+title: README
#+date: <2026-01-15 Thu>
#+author: Julien Chastang
#+email: chastang@ucar.edu
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 30.2 (Org mode 9.7.39)

* AMS 2026 Case Study
:PROPERTIES:
:CUSTOM_ID: h-CF586FCF
:END:

** Introduction
:PROPERTIES:
:CUSTOM_ID: h-0F8FBAA8
:END:

This case study builds on work by Professor Brian Mapes during the fall semester of 2025 for a Weather Analysis class at the University of Miami. Professor Mapes used a dedicated PyAOS JupyterHub environment provided by UCAR/NSF Unidata to develop a workflow in which global atmospheric wind fields from the [[https://thredds.ucar.edu/thredds/catalog/grib/NCEP/GFS/Global_onedeg/catalog.html?dataset=grib/NCEP/GFS/Global_onedeg/Best][GFS 1-degree Best dataset]], valid near the current time, are accessed and diagnostic quantities are computed programmatically in a Jupyter notebook using the [[https://ajdawson.github.io/windspharm/][Windspharm]] Python package. In particular, the workflow applies a [[https://en.wikipedia.org/wiki/Helmholtz_decomposition][Helmholtz decomposition]] to derive the velocity potential field at 200 hPa.

The resulting diagnostic fields are written to NetCDF and visualized using the cloud-hosted IDV desktop running within the same JupyterHub. Within the IDV, the velocity potential field is overlaid with contemporaneous global infrared satellite imagery, allowing direct visual comparison between large-scale divergence circulation patterns and convective cloud structures. Together, the notebook and IDV bundle illustrate a unified, browser-based workflow that integrates data access, dynamical diagnostics, and interactive visualization. The following section describes the two files involved for this case study.

** Relevant Files and Python Environment
:PROPERTIES:
:CUSTOM_ID: h-FEB28187
:END:

Two files are included in this directory:

1. ~gfs_200hpa_helmholtz_decomposition.ipynb~
   This notebook demonstrates a workflow for computing a Helmholtz decomposition of global atmospheric wind fields. GFS wind data are accessed from Unidata's THREDDS catalog via OPeNDAP, subset by time and pressure level, and processed using Windspharm to compute streamfunction and velocity potential. The resulting diagnostic fields are written to NetCDF for subsequent visualization. The Python ~environment.yml~ required to run this notebook is found one directory level up.
2. ~gfs_200hpa_helmholtz_decomposition.xidv~
   This IDV bundle reads the NetCDF output produced by the notebook and visualizes the derived fields in combination with infrared satellite imagery corresponding to the same time step. The data are displayed using a Mollweide projection.

** How to Run
:PROPERTIES:
:CUSTOM_ID: h-3BF74FF4
:END:

1. Go to https://jupyterhub.unidata.ucar.edu and log in using CILogon.
2. In JupyterLab, open a Terminal (File → New → Terminal) and run the following commands to download the required files:
   - ~wget https://raw.githubusercontent.com/Unidata/science-gateway/refs/heads/master/jupyter-images/fall-2025/rsmas/environment.yml~
   - ~wget https://raw.githubusercontent.com/Unidata/science-gateway/refs/heads/master/jupyter-images/fall-2025/rsmas/ams2026-case-study/gfs_200hpa_helmholtz_decomposition.ipynb~
   - ~wget https://raw.githubusercontent.com/Unidata/science-gateway/refs/heads/master/jupyter-images/fall-2025/rsmas/ams2026-case-study/gfs_200hpa_helmholtz_decomposition.xidv~
3. In the same Terminal, create the conda environment:
   - ~mamba env create -f environment.yml~
   This step may take a few minutes to complete.
4. Open ~gfs_200hpa_helmholtz_decomposition.ipynb~ in JupyterLab. From the top menu, select Kernel → Change Kernel, choose ~rsmas25f~, and then run all cells in the notebook. This produces a NetCDF output file containing the results of the analysis.
5. From the JupyterLab launcher, start the Unidata Desktop (IDV) and open the ~gfs_200hpa_helmholtz_decomposition.xidv~ bundle to visualize the results.
