###
# LDM
###
version: '3'

ldm:
  image: unidata/ldm-docker:latest
  container_name: ldm
  # restart: always
  volumes:
    - ~/etc/:/home/ldm/etc/
    - ~/queues:/home/ldm/var/queues/
    - ~/logs/ldm/:/home/ldm/var/logs/
  ports:
    - "388:388"
  ulimits:
    nofile:
      soft: 1024
      hard: 1024
  env_file:
    - "compose.env"
