###
# LDM
###
ldm:
  # restart: always
  image: unidata/ldm-docker:6.13.6
  container_name: ldm
  volumes:
    - ~/etc/:/home/ldm/etc/
    - ~/queues:/home/ldm/var/queues/
    - ~/logs/ldm/:/home/ldm/var/logs/
  ports:
    - "388:388"
  ulimits:
    nofile:
      soft: 1024
      hard: 1024
  env_file:
    - "compose.env"
