#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: docker-readme
#+DATE: <2017-03-03 Fri>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)

#+PROPERTY: header-args :noweb yes :tangle no

* Org Setup :noexport:

#+BEGIN_SRC emacs-lisp :results silent :exports none
  (setq org-confirm-babel-evaluate nil)
  (setq org-export-babel-evaluate nil)
#+END_SRC

* Docker Installation

The ~xsede-jetstream~ project is heavily dependent on Docker.  Herein are some instructions to help you get going with Docker.

** Linux VM or Bare Metal Linux

Always think before typing the following commands as ~root~ user!

*** System Maintenance

Do the usual maintenance via ~apt-get~ or ~yum~. Also install ~git~ for good measure.

**** apt-get

#+BEGIN_SRC sh :eval no
  apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade && \
      apt-get -y install git
#+END_SRC

**** yum

#+BEGIN_SRC sh :eval no
 yum -y update && yum -y install git
#+END_SRC

*** Install Docker

Again, think before you type.

#+BEGIN_SRC sh :eval no
  curl -sSL get.docker.com | sh
  usermod -aG docker <username>
#+END_SRC

*** Install docker-compose

#+BEGIN_SRC org :noweb-ref dcompose-version :exports none
 1.11.2
#+END_SRC

#+BEGIN_SRC sh :eval no :noweb yes
  curl -L https://github.com/docker/compose/releases/download/<<dcompose-version>>/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

  chmod +x /usr/local/bin/docker-compose
#+END_SRC

*** Start Docker Daemon

As ~root~ user, make sure Docker is available as a daemon. You can issue one of the following commands depending on your flavor of Linux.

#+BEGIN_SRC sh :eval no
  service start docker
#+END_SRC

or 

#+BEGIN_SRC sh :eval no
  systemctl enable docker.service
  systemctl start docker.service
#+END_SRC

*** Reboot

Now reboot the machine:

#+BEGIN_SRC sh :eval no
  reboot now
#+END_SRC

Log back into Linux machine or VM.

*** Docker Hello World

Run this container to make sure the docker install has gone smoothly:

#+BEGIN_SRC sh :eval no
  docker run hello-world
#+END_SRC

** Other Environments (e.g., macOS, Windows)

For other environments, see [[https://docs.docker.com/engine/installation/][the official docker installation documentation]].
