name: sau-spring-2025
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - geopandas
  - mlxtend
  - statsmodels
  - plotly
  - pycaret
  - nltk
  - spacy
  - gensim
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - palmerpenguins
