name: rsmas25f
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - cartopy
  - earthaccess
  - gif
  - h5netcdf
  - hdf5
  - ipywidgets
  - iris
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pip
  - siphon
  - windspharm
  - xarray
  - pip:
      - mseplots-pkg
