###
# JupyterHub + nginx
###

version: '3'

services:
  jupyter:
    image: unidata/unidatahub
    container_name: jupyter
    # restart: always
    volumes:
      # Directories outside of the container that need to be accessible
      - ~/config:/etc/jupyterhub
      - ~/logs/jupyter:/var/log
      - ~/ssl/:/etc/jupyterhub/ssl/
      - /notebooks:/notebooks
      - /scratch:/scratch
    ports:
      - "8000:8000"
      - "443:443"
    env_file:
      - "compose.env"
  web:
    image: nginx
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
