###
# JupyterHub + nginx
###

version: '3'

services:
  jupyter:
    image: unidata/unidatahub
    container_name: jupyter
    # restart: always
    volumes:
      # Directories outside of the container that need to be accessible
      - ~/config:/etc/jupyterhub
      - ~/logs/jupyter:/var/log
      - ~/config/ssl/:/etc/jupyterhub/ssl/
      - /notebooks:/notebooks
      - /scratch:/scratch
      - /wrangler/backup-notebooks:/backup-notebooks
      - ./login.html:/opt/conda/share/jupyterhub/templates/login.html
    ports:
      - "8000:8000"
      - "443:443"
    env_file:
      - "compose.env"
  web:
    image: nginx
    container_name: nginx
    # restart: always
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
