###
# JupyterHub
###

version: '3'

services:
  jupyter:
    image: unidata/unidatahub
    container_name: jupyter
    # restart: always
    volumes:
      # Directories outside of the container that need to be accessible
      - ~/config:/etc/jupyterhub
      - ~/logs/jupyter:/var/log
      - /notebooks:/notebooks
      - /scratch:/scratch
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    env_file:
      - "compose.env"
