version: '3'

services:

  ###
  # LDM
  ###
  ldm:
    image: unidata/ldm-docker:latest
    container_name: ldm
    # restart: always
    volumes:
      - ~/etc/:/home/ldm/etc/
      - /data/:/home/ldm/var/data/
      - /data/:/data/
      - /data/ldm/queues:/home/ldm/var/queues/
      - /data/ldm/logs/:/home/ldm/var/logs/
      - ./cron/:/var/spool/cron/
    ports:
      - "388:388"
    ulimits:
      nofile:
        soft: 64
        hard: 64
    env_file:
        - "compose.env"
  
  ###
  # TDM
  ###
  tdm:
    image: unidata/tdm-docker:latest
    container_name: tdm
    # restart: always
    volumes:
        - /data/:/data/
        - ~/tdsconfig/:/usr/local/tomcat/content/thredds/
        - ~/logs/tdm/:/usr/local/tomcat/content/tdm/
    env_file:
        - "compose.env"
