###
# LDM
###
ldm:
  # restart: always
  image: unidata/ldm-docker:6.13.6
  container_name: ldm
  restart: always
  volumes:
    - ~/etc/:/home/ldm/etc/
    - /data/:/home/ldm/var/data/
    - /data/:/data/
    - /data/queues:/home/ldm/var/queues/
    - /data/logs/ldm/:/home/ldm/var/logs/
    - ./cron/:/var/spool/cron/
  ports:
    - "388:388"
  ulimits:
    nofile:
      soft: 64
      hard: 64
