#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t
#+OPTIONS: H:6
#+TITLE: Creating Webserver VM on Jetstream
#+DATE: <2017-08-14 Mon>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)
#+STARTUP: content

#+PROPERTY: header-args :noweb yes :eval no

* Creating a Science Gateway VM on Jetstream
  :PROPERTIES:
  :CUSTOM_ID: h-49CACBE8
  :END:

** Create a Science Gateway VM on Jetstream
   :PROPERTIES:
   :CUSTOM_ID: h-593C3161
   :END:
Create an ~m1.small~ VM with the  [[file:../../openstack/readme.org::#h-03303143][Jetstream OpenStack API]]. Work with Unidata system administrator staff to have this VM's IP address resolve to =science-gateway.unidata.ucar.edu=.
** Clone the science-gateway Repository
   :PROPERTIES:
   :CUSTOM_ID: h-1EA54D54
   :END:

 We will be making heavy use of the ~Unidata/science-gateway~ git repository.

#+begin_src shell :tangle no :exports code
  git clone https://github.com/Unidata/science-gateway ~/science-gateway
#+END_SRC

** Build the Science Gateway Docker Container
   :PROPERTIES:
   :CUSTOM_ID: h-4A66EE99
   :END:

From the =~/science-gateway/vms/science-gateway= directory:

#+begin_src shell :tangle no :exports code
  docker build -t unidata/science-gateway:latest .
#+END_SRC

** Prepare Science Gateway VM for Docker and docker-compose
   :PROPERTIES:
   :CUSTOM_ID: h-D311EB0F
   :END:

With the help of Docker and ~docker-compose~, starting a VM containing an IDD archiver is relatively simple. [[file:../../vm-init-readme.org::#h-786799C4][See here to install Docker and docker-compose]].

** Logging
   :PROPERTIES:
   :CUSTOM_ID: h-7FF2F781
   :END:

Create the following nginx log directory:

#+begin_src shell
  mkdir -p /logs/nginx
 #+END_SRC

** Ports 80, 443
   :PROPERTIES:
   :CUSTOM_ID: h-5BF405FC
   :END:

[[file:../../openstack/readme.org::#h-D6B1D4C2][Open ports]] ~80~, and ~443~ on the Science Gateway VM via OpenStack.

** DNS Name
   :PROPERTIES:
   :CUSTOM_ID: h-F47D384F
   :END:
Work with Unidata sys admin staff to have the IP address of this VM point to science-gateway.unidata.ucar.edu.
** Obtain HTTPS Certificates
   :PROPERTIES:
   :CUSTOM_ID: h-CE6457C8
   :END:

Work with system admin staff to obtain an HTTPS key and certificate from a certificate authority such as InCommon. Put them in =/etc/ssl/science-gateway/=, e.g., =science-gateway.unidata.ucar.edu.key= and =science-gateway.unidata.ucar.edu.crt=. Ensure these are owned by root and set to read only. The certificate must include intermediate certificates for security purposes. You can test the security quality of the website with [[https://www.ssllabs.com/ssltest/][ssllabs test]].

*** OCSP stapling
    :PROPERTIES:
    :CUSTOM_ID: h-A7B71EC8
    :END:

[[https://en.wikipedia.org/wiki/OCSP_stapling][OCSP (Online Certificate Status Protocol) stapling]] is recommended for web server communication privacy and efficiency. To enable this feature in an nginx server, have a file containing the intermediate and root certificates. Simply take the full chain certificate file described above and remove the base certificate leaving the intermediate and root certificates only. Call this file =ca-certs.pem= and put it in the =/etc/ssl/= directory along side the ~key~ and ~crt~ file described above. It will be mounted into the container with [[file:../../../vms/science-gateway/docker-compose.yml][docker-compose.yml]] and referred to in =nginx.conf= with

#+begin_src fundamental
  ssl_trusted_certificate /etc/nginx/ca-certs.pem
#+END_SRC

** Start Science Gateway
   :PROPERTIES:
   :CUSTOM_ID: h-B30CBDF8
   :END:

Once you have done the work of setting up nginx related directories,

#+begin_src shell
  docker-compose up -d
#+END_SRC

to start the web server.

