name: uwb-fall-2024
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - arm_pyart
  - xarray==2023.10.1
  - tensorflow
  - geopandas
