name: mvu24f
channels:
  - rttools
  - conda-forge
  - defaults
dependencies:
  # Required by JupyterLab
  - python=3.10
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - pandas
  - scipy
  - metpy
  - xarray
  - scikit-learn
  - wrf-python
  - cartopy
  - seaborn
  - netcdf4
  - pyorbital
  - pytz
  - siphon
  - statsmodels
  - pip
  - cfgrib
  - climlab
  - climlab-rrtmg
  - typhon
  - ipympl
  - proplot
  - pyarts=2.5.12
  - pip:
    - miepython
variables:
  ARTS_DATA_PATH: /share/share/ESCI345/arts-xml-data/
