name: uwb-fall-2023
channels:
 - conda-forge
 - defaults
 - conda-forge
 - anaconda-fusion
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - altair
  - aospy
  - argopy
  - arm_pyart
  - bokeh
  - build
  - cartopy
  - celluloid
  - cfgrib
  - cmocean
  - dask
  - datashader
  - distributed
  - fsspec
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - h5py
  - hatchling
  - hvplot
  - ipykernel
  - ipympl
  - ipywidgets
  - iris
  - jupyterlab
  - matplotlib
  - matplotlib-inline
  - metpy
  - nbdime
  - nc-time-axis
  - netcdf-fortran
  - netcdf4
  - nodejs
  - numcodecs
  - numpy=1.19.5
  - pandas<1.1.0
  - pip
  - plotly
  - plotnine
  - pyresample
  - pytest
  - python
  - python-graphviz
  - satpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - siphon
  - twine
  - vega_datasets
  - xarray
  - xesmf
  - xgcm
  - zarr
