#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t
#+TITLE: Creating an IDD Relay on Jetstream
#+DATE: <2017-03-17 Fri>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)

#+PROPERTY: header-args :eval no :tangle no

* Creating an IDD Relay on Jetstream
  :PROPERTIES:
  :CUSTOM_ID: h:840E89CB
  :END:
** Create an IDD Relay VM on Jetstream
   :PROPERTIES:
   :CUSTOM_ID: h:4BF1C37C
   :END:

Create an ~m1.medium~ VM with the [[https://github.com/Unidata/xsede-jetstream/blob/master/openstack/readme.md][Jetstream OpenStack API]]. Work with Unidata system administrator staff to have this VM's IP address resolve to =idd-relay-jetstream.unidata.ucar.edu=.

** Clone the xsede-jetstream Repository
   :PROPERTIES:
   :CUSTOM_ID: h:7544DE64
   :END:

We will be making heavy use of the ~Unidata/xsede-jetstream~ git repository.

#+BEGIN_SRC shell :eval no
  git clone https://github.com/Unidata/xsede-jetstream
#+END_SRC

** Start IDD Relay With Docker and docker-compose
   :PROPERTIES:
   :CUSTOM_ID: h:C89E3FF5
   :END:

With the help of Docker and ~docker-compose~, starting a VM containing an IDD relay is simple. There are a few directories you will need to map from outside to within the container. [[https://github.com/Unidata/xsede-jetstream/blob/master/docker-readme.md][See here to install Docker and docker-compose]]. 

** ~/etc Directory
   :PROPERTIES:
   :CUSTOM_ID: h:E4AB4451
   :END:

This =~/etc= directory will contain your LDM configuration files.
#+BEGIN_SRC shell :tangle ../../../vms/idd-relay/relay-install.sh :shebang "#!/bin/bash"
  mkdir -p ~/etc
  cp ~/xsede-jetstream/vms/idd-relay/etc/* ~/etc/
#+END_SRC

You may have to tailor the =ldmd.conf= to your data feed requirements. Also edit the =registry.xml= file to update the ~hostname~ element so that Real-Time IDD Statistics can be properly reported. Finally, you may have to adjust the size of the queue currently at 10GBs.

** ~/queues Directory
   :PROPERTIES:
   :CUSTOM_ID: h:F3D77CEF
   :END:

This =~/queues= directory will contain the LDM queue file.

#+BEGIN_SRC shell :tangle ../../../vms/idd-relay/relay-install.sh
  mkdir -p ~/queues
#+END_SRC

** ~/logs Directory
   :PROPERTIES:
   :CUSTOM_ID: h:515DAD84
   :END:


Create the LDM =logs= directory.

#+BEGIN_SRC shell :tangle ../../../vms/idd-relay/relay-install.sh
  mkdir -p ~/logs/ldm
#+END_SRC

** Port 388
   :PROPERTIES:
   :CUSTOM_ID: h:FB14DD93
   :END:

Open LDM port ~388~ so that this VM may function as an IDD relay node. [[https://github.com/Unidata/xsede-jetstream/blob/master/openstack/readme.md#h:D6B1D4C2][See here]] for more information on opening ports.

** docker-compose.yml
   :PROPERTIES:
   :CUSTOM_ID: h:95441A93
   :END:

Based on the directory set we have defined, the =docker-compose.yml= file will look something like:

#+INCLUDE: "../../../vms/idd-relay/docker-compose.yml" src yaml

*** LDM Environment Variable Parameterization
    :PROPERTIES:
    :CUSTOM_ID: h:031CD94A
    :END:

You can provide additional LDM parameterization via the =compose.env= file referenced in the =docker-compose.yml= file.

#+INCLUDE: "../../../vms/idd-relay/compose.env" src shell

** Start the IDD Relay Node
   :PROPERTIES:
   :CUSTOM_ID: h:80DA881B
   :END:

To start the IDD relay node:

#+BEGIN_SRC shell
  # wherever you cloned the repo above
  cd ~/xsede-jetstream/vms/idd-relay/
  docker-compose up -d
#+END_SRC
