#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t

#+TITLE: readme
#+DATE: <2017-03-02 Thu>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)

* Running VMs on Jetstream with OpenStack
  :PROPERTIES:
  :CUSTOM_ID: h:90A8A74D
  :END:
** Install Docker
   :PROPERTIES:
   :CUSTOM_ID: h:DE5B47F1
   :END:

[[https://github.com/Unidata/xsede-jetstream/blob/master/docker-readme.md][Install Docker]] in your computing environment because we will be interacting with the OpenStack Jetstream API via Docker. This step should make our lives easier.

** Clone the xsede-jetstream Repository
   :PROPERTIES:
   :CUSTOM_ID: h:968FA51C
   :END:

We will be making heavy use of the ~Unidata/xsede-jetstream~ git repository.

#+BEGIN_SRC sh :eval no
  git clone https://github.com/Unidata/xsede-jetstream
#+END_SRC

** Build Docker Container
   :PROPERTIES:
   :CUSTOM_ID: h:4A9632CC
   :END:

#+BEGIN_SRC sh :eval no
  cd xsede-jetstream/openstack
  docker build -t openstack-client .
#+END_SRC

** API Setup
   :PROPERTIES:
   :CUSTOM_ID: h:CBD5EC54
   :END:

We will be using the Jetstream API directly and via convenience scripts. 

*** openrc.sh
    :PROPERTIES:
    :CUSTOM_ID: h:8B3E8EEE
    :END:

The next part involves downloading the =openrc.sh= file to work with our OpenStack allocation. You will have first login to the OpenStack TACC dashboard which will necessitate a password reset. Unfortunately, this login is not the same as the Jetstream Atmosphere web interface login.

**** Resetting Password
     :PROPERTIES:
     :CUSTOM_ID: h:3E2185E5
     :END:

[[https://portal.tacc.utexas.edu/password-reset/][Reset your OpenStack TACC dashboard password]]. 

**** Download openrc.sh
     :PROPERTIES:
     :CUSTOM_ID: h:B34CC3AF
     :END:

Download the =openrc.sh= file [[https://iujetstream.atlassian.net/wiki/display/JWT/Setting+up+openrc.sh][according to the Jetstream API instructions]]. See "Use the Horizon dashboard to generate openrc.sh". Use the IU: https://jblb.jetstream-cloud.org/dashboard not the TACC dashboard.  In the Jetstream Dashboard, navigate to ~Access & Security~, ~API Access~ to download =openrc.sh= (v3).

Edit the =openrc.sh= file and the supply the TACC resource ~OS_PASSWORD~:

#+BEGIN_SRC sh :eval no
  export OS_PASSWORD="changeme!"
#+END_SRC

Comment out

#+BEGIN_SRC sh :eval no
# echo "Please enter your OpenStack Password: "
# read -sr OS_PASSWORD_INPUT
#+END_SRC

*** Fire Up Container and More Setup
    :PROPERTIES:
    :CUSTOM_ID: h:30B73273
    :END:

Start the ~openstack-client~ container with

#+BEGIN_SRC sh :eval no
  sh openstack.sh
#+END_SRC

**** Create ssh Keys
     :PROPERTIES:
     :CUSTOM_ID: h:EE48476C
     :END:

Do this step once. This step of ssh key generation is important. In our experience, we have not had good luck with pre-existing keys. You may have to generate a new one. Be careful with the ~-f~ argument below. We are operating under one allocation so make sure your key names do not collide with other users. Name your key something like ~<some short somewhat unique id>-${OS_PROJECT_NAME}-api-key~. Then you add your public key the TACC dashboard with ~nova keypair-add~.

 #+BEGIN_SRC sh :eval no
  ssh-keygen -b 2048 -t rsa -f <key-name> -P ""
  nova keypair-add --pub-key id_rsa.pub <key-name>
 #+END_SRC

Your =.ssh= directory was mounted from outside the Docker container you are currently running. Your public/private key should be saved there. Don't lose it or else you may not be able to delete the VMs you are about to create.

**** Testing Your Setup
     :PROPERTIES:
     :CUSTOM_ID: h:257FBBBE
     :END:

At this point, you should be able to run ~glance image-list~ which should yield something like: 

#+TBLNAME: image-list
| ID                                   | Name                               |
|--------------------------------------+------------------------------------|
| fd4bf587-39e6-4640-b459-96471c9edb5c | AutoDock Vina Launch at Boot       |
| 02217ab0-3ee0-444e-b16e-8fbdae4ed33f | AutoDock Vina with ChemBridge Data |
| b40b2ef5-23e9-4305-8372-35e891e55fc5 | BioLinux 8                         |
|--------------------------------------+------------------------------------|

If not, check your setup.

** Working with Jetstream API to Create VMs
   :PROPERTIES:
   :CUSTOM_ID: h:03303143
   :END:
*** IP Numbers
    :PROPERTIES:
    :CUSTOM_ID: h:5E7A7E65
    :END:

We are ready to fire up VMs. First create an IP number which we will be using shortly:

#+BEGIN_SRC sh :eval no
  nova floating-ip-create public
  nova floating-ip-list
#+END_SRC

or you can just ~nova floating-ip-list~ if you have IP numbers left around from previous VMs.

*** Boot VM
    :PROPERTIES:
    :CUSTOM_ID: h:EA17C2D9
    :END:

Now you can boot up a VM with something like the following command:

#+BEGIN_SRC sh :eval no
  boot.sh -n unicloud -k <key-name> -s m1.medium -ip 149.165.157.137
#+END_SRC

The ~boot.sh~ command takes a VM name, [[#h:EE48476C][ssh key name]], size, and IP number created earlier, and optionally a network name or UUID. See ~boot.sh -h~ and ~nova flavor-list~ for more information.

*** Create and Attach Data Volumes
    :PROPERTIES:
    :CUSTOM_ID: h:9BEEAB97
    :END:

You can create data volumes via the open stack ~cinder~ interface. As an example, here, we will be creating a 750GB ~data~ volume. You will subsequently attach the data volume to your VM with ~nova~ commands:
 
#+BEGIN_SRC sh :eval no
  cinder create 750 --display-name data

  cinder list && nova list

  nova volume-attach <vm-uid-number> <volume-uid-number> auto
#+END_SRC

You will then be able to log in to your VM and mount your data volume with typical Unix ~mount~, ~umount~, and ~df~ commands.

There is a ~mount.sh~ convenience script to mount *uninitialized* data volumes.

*** ssh Into New VM
    :PROPERTIES:
    :CUSTOM_ID: h:D961F6F8
    :END:

~ssh~ into that newly minted VM:

#+BEGIN_SRC :eval no
  ssh ubuntu@149.165.157.137
#+END_SRC

If you are having trouble logging in, you may try to delete the =~/.ssh/known_hosts= file. If you still have trouble, try ~nova stop <vm-uid-number>~ followed by ~nova start <vm-uid-number>~.

