#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t

#+TITLE: readme
#+DATE: <2017-03-02 Thu>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)

* Running VMs on Jetstream with OpenStack
  :PROPERTIES:
  :CUSTOM_ID: h:90A8A74D
  :END:
** Introduction
   :PROPERTIES:
   :CUSTOM_ID: h:11F59F95
   :END:

It is preferable to interface with the XSEDE Jetstream cloud via the [[https://use.jetstream-cloud.org/application/dashboard][Atmosphere web interface]]. However, this web dashboard is limited in two important ways:

  1. Users cannot obtain VMs with static IPs
  2. Users cannot open low number ports (i.e., < 1024)

If you are in either of these scenarios you have to interface with Jetstream via the OpenStack API. The problem here is that you have to do some initial setup which is somewhat painful but that you do only once. After that, you can interface with the Jetstream OpenStack command line via =openstack.sh= line to:

  - Create IP Numbers
  - Create VMs
  - Tear down VMs
  - Create Data Volumes
  - Attach Data Volumes

** Install Docker (Do This Once)
   :PROPERTIES:
   :CUSTOM_ID: h:DE5B47F1
   :END:

[[https://github.com/Unidata/xsede-jetstream/blob/master/docker-readme.md][Install Docker]] in your computing environment because we will be interacting with the OpenStack Jetstream API via Docker. This step should make our lives easier.

** Clone the xsede-jetstream Repository (Do This Once)
   :PROPERTIES:
   :CUSTOM_ID: h:968FA51C
   :END:

We will be making heavy use of the ~Unidata/xsede-jetstream~ git repository.

#+BEGIN_SRC sh :eval no
  git clone https://github.com/Unidata/xsede-jetstream
#+END_SRC

** Pull or Build Docker Container (Do This Once)
   :PROPERTIES:
   :CUSTOM_ID: h:4A9632CC
   :END:

#+BEGIN_SRC sh :eval no
  cd xsede-jetstream/openstack
#+END_SRC

At this point, you can either pull or build the ~xsede-jetstream~ container:

*** Pull Container
    :PROPERTIES:
    :CUSTOM_ID: h:B5690030
    :END:
#+BEGIN_SRC sh :eval no
  docker pull unidata/xsede-jetstream
#+END_SRC

*** Build Container
    :PROPERTIES:
    :CUSTOM_ID: h:1C54F677
    :END:
#+BEGIN_SRC sh :eval no
  docker build -t unidata/xsede-jetstream .
#+END_SRC

** API Setup
   :PROPERTIES:
   :CUSTOM_ID: h:CBD5EC54
   :END:

We will be using the Jetstream API directly and via convenience scripts. 

*** Download and Edit openrc.sh (Do This Once)
    :PROPERTIES:
    :CUSTOM_ID: h:8B3E8EEE
    :END:

The next part involves downloading the =openrc.sh= file to work with our OpenStack allocation. You will have first login to the OpenStack TACC dashboard which will necessitate a password reset. Unfortunately, this login is not the same as the Jetstream Atmosphere web interface login. Also, follow the usual password advice of not reusing passwords as this password will end up in your OpenStack environment and [[#h:9C0700C5][you may want to add it]] in the =openrc.sh= file for convenience.

**** Resetting Password
     :PROPERTIES:
     :CUSTOM_ID: h:3E2185E5
     :END:

[[https://portal.tacc.utexas.edu/password-reset/][Reset your OpenStack TACC dashboard password]]. 

**** Download openrc.sh
     :PROPERTIES:
     :CUSTOM_ID: h:B34CC3AF
     :END:

Download the =openrc.sh= file [[https://iujetstream.atlassian.net/wiki/display/JWT/Setting+up+openrc.sh][according to the Jetstream API instructions]]. See "Use the Horizon dashboard to generate openrc.sh". Use the IU: https://jblb.jetstream-cloud.org/dashboard not the TACC dashboard.  In the Jetstream Dashboard, navigate to ~Access & Security~, ~API Access~ to download =openrc.sh= (v3). (In reality, it will be named something like =TG-ATM160027-openrc.sh=. You can rename it to =openrc.sh=, if you want.)

**** Edit openrc.sh Password (Optional)
     :PROPERTIES:
     :CUSTOM_ID: h:9C0700C5
     :END:

Optionally, for convenience, you may wish to add your password to the =openrc.sh= file. Again, follow the usual advice of not reusing passwords as this password will end up in your OpenStack environment.

Edit the =openrc.sh= file and the supply the TACC resource ~OS_PASSWORD~ you [[#h:8B3E8EEE][reset earlier]]:

#+BEGIN_SRC sh :eval no
  export OS_PASSWORD="changeme!"
#+END_SRC

Comment out

#+BEGIN_SRC sh :eval no
# echo "Please enter your OpenStack Password: "
# read -sr OS_PASSWORD_INPUT
#+END_SRC

*** Fire Up Container and More Setup
    :PROPERTIES:
    :CUSTOM_ID: h:30B73273
    :END:
**** openstack.sh
     :PROPERTIES:
     :CUSTOM_ID: h:5F4AFF6F
     :END:

Start the ~unidata/xsede-jetstream~ container with =openstack.sh= convenience script. The script take a ~-o~ argument for your =openrc.sh= file and a ~-s~ argument for the directory containing or will contain your ssh keys (e.g., =/home/jane/xsede-jetstream/openstack/ssh= or a new directory that will contain contain your Jetstream OpenStack keys that we will be creating shortly). *Both arguments must be supplied with fully qualified path names.*

#+BEGIN_SRC sh :eval no
  chmod +x openstack.sh
  ./openstack.sh -o </path/to/your openrc.sh file> -s </path/to/your/ssh directory>
#+END_SRC

Subsequently, when interacting with Jetstream via OpenStack API now and in the future, you will be using this container to create VMs, mount volumes, etc.

**** Create ssh Keys (Do This Once)
     :PROPERTIES:
     :CUSTOM_ID: h:EE48476C
     :END:

This step of ssh key generation is important. In our experience, we have not had good luck with preexisting keys. You may have to generate a new one. Be careful with the ~-f~ argument below. We are operating under one allocation so make sure your key names do not collide with other users. Name your key something like ~<some short somewhat unique id>-${OS_PROJECT_NAME}-api-key~. Then you add your public key the TACC dashboard with ~nova keypair-add~.

 #+BEGIN_SRC sh :eval no
  cd ~/.ssh
  ssh-keygen -b 2048 -t rsa -f <key-name> -P ""
  # may get a deprecation warning here
  nova keypair-add --pub-key <key-name>.pub <key-name>
  # go back to home directory
  cd
 #+END_SRC

The =ssh= directory was mounted from outside the Docker container you are currently running. Your public/private key should be saved there. Don't lose it or else you may not be able to delete the VMs you are about to create.

**** Testing Setup
     :PROPERTIES:
     :CUSTOM_ID: h:257FBBBE
     :END:

At this point, you should be able to run ~glance image-list~ which should yield something like: 

#+TBLNAME: image-list
| ID                                   | Name                               |
|--------------------------------------+------------------------------------|
| fd4bf587-39e6-4640-b459-96471c9edb5c | AutoDock Vina Launch at Boot       |
| 02217ab0-3ee0-444e-b16e-8fbdae4ed33f | AutoDock Vina with ChemBridge Data |
| b40b2ef5-23e9-4305-8372-35e891e55fc5 | BioLinux 8                         |
|--------------------------------------+------------------------------------|

If not, check your setup.

** Working with Jetstream API to Create VMs
   :PROPERTIES:
   :CUSTOM_ID: h:03303143
   :END:

At this point, we are past the hard work. You will you will employ the ~unidata/xsede-jetstream~ container accessed via the =openstack.sh= convenience script to

  - Create IP Numbers
  - Create VMs
  - Tear down VMs
  - Create Data Volumes
  - Attach Data Volumes

If you have not done so already:

#+BEGIN_SRC sh :eval no
  ./openstack.sh -o </path/to/your openrc.sh file> -s </path/to/your/ssh directory>
#+END_SRC
   
*** IP Numbers
    :PROPERTIES:
    :CUSTOM_ID: h:5E7A7E65
    :END:

We are ready to fire up VMs. First create an IP number which we will be using shortly:

#+BEGIN_SRC sh :eval no
  nova floating-ip-create public
  nova floating-ip-list
#+END_SRC

or you can just ~nova floating-ip-list~ if you have IP numbers left around from previous VMs.

*** Boot VM
    :PROPERTIES:
    :CUSTOM_ID: h:EA17C2D9
    :END:

**** Create VM
    :PROPERTIES:
    :CUSTOM_ID: h:7E8034E7
    :END:
Now you can boot up a VM with something like the following command:

#+BEGIN_SRC sh :eval no
  boot.sh -n unicloud -k <key-name> -s m1.medium -ip 149.165.157.137
#+END_SRC

The ~boot.sh~ command takes a VM name, [[#h:EE48476C][ssh key name]] defined earlier, size, and IP number created earlier, and optionally a network name or UUID. See ~boot.sh -h~ and ~nova flavor-list~ for more information.

**** SSH Into New VM
    :PROPERTIES:
    :CUSTOM_ID: h:10ACA1BC
    :END:

At this point, you can ~ssh~ into our newly minted VM. Explicitly providing the key name with the ~ssh~ ~-i~ argument and a user name (e.g., ~ubuntu~ or ~centos~) may be important:

#+BEGIN_SRC sh :eval no
  ssh -i ~/.ssh/<key-name> ubuntu@149.165.157.137
#+END_SRC

At this point, you might see

#+BEGIN_SRC sh :eval no
  ssh: connect to host 149.165.157.137 port 22: No route to host
#+END_SRC

Usually waiting for a few minutes resolves the issue. If you are still have trouble, try ~nova stop <vm-uid-number>~ followed by ~nova start <vm-uid-number>~.

**** Adding Additional SSH Keys (Optional)
     :PROPERTIES:
     :CUSTOM_ID: h:A66BED33
     :END:

Once you are in your VM, it is probably best to add additional ssh public keys into the ~authorized_keys~ file to make logging in easier from whatever host you are connecting from.

*** Create and Attach Data Volumes
    :PROPERTIES:
    :CUSTOM_ID: h:9BEEAB97
    :END:

You can create data volumes via the open stack ~cinder~ interface. As an example, here, we will be creating a 750GB ~data~ volume. You will subsequently attach the data volume to your VM with ~nova~ commands:
 
#+BEGIN_SRC sh :eval no
  cinder create 750 --display-name data

  cinder list && nova list

  nova volume-attach <vm-uid-number> <volume-uid-number> auto
#+END_SRC

You will then be able to log in to your VM and mount your data volume with typical Unix ~mount~, ~umount~, and ~df~ commands.

There is a ~mount.sh~ convenience script to mount *uninitialized* data volumes. Run this script as root or sudo on the newly created VM not from the OpenStack CL.

*** Tearing Down VMs
    :PROPERTIES:
    :CUSTOM_ID: h:1B38941F
    :END:

There is also a ~teardown.sh~ convenience script for deleting VMs. Be sure to ~umount~ any data volumes before deleting a VM. For example,

#+BEGIN_SRC sh :eval no
  umount /data
#+END_SRC

then from the OpenStack CL

#+BEGIN_SRC sh :eval no
  teardown.sh -n unicloud -ip 149.165.157.137
#+END_SRC

For now, you have to supply the IP number even though the script should theoretically be smart enough to figure that out.
