name: uah24s
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas
  - pip
  - xarray
  - ipywidgets
  - python-awips
  - scikit-learn
  - tobac
  - s3fs
  - arm_pyart
  - netCDF4
  - zarr
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - palmerpenguins
    - tensorflow==2.15.post1
    - nvidia-cublas-cu12==12.2.5.6
    - nvidia-cuda-cupti-cu12==12.2.142
    - nvidia-cuda-nvcc-cu12==12.2.140
    - nvidia-cuda-nvrtc-cu12==12.2.140
    - nvidia-cuda-runtime-cu12==12.2.140
    - nvidia-cudnn-cu12==8.9.4.25
    - nvidia-cufft-cu12==11.0.8.103
    - nvidia-curand-cu12==10.3.3.141
    - nvidia-cusolver-cu12==11.5.2.141
    - nvidia-cusparse-cu12==12.1.2.141
    - nvidia-nccl-cu12==2.16.5
    - nvidia-nvjitlink-cu12==12.2.140
