#+title: Progress Report: Next Phase of Unidata Cloud-hosted Data Services: Transitioning and Expanding Operations to Jetstream2 and Investigating New Hardware Capabilities
#+author: Mohan Ramamurthy (PI), Julien Chastang (co-I), Ana Espinoza

#+bibliography: jetstream.bib

#+options: toc:nil num:t date:nil author:nil auto-id:t

#+begin_src emacs-lisp :results silent :exports none
  (require 'oc-csl)
#+end_src

#+cite_export: csl ~/git/science-gateway/.org/proposals/jetstream2-research/american-geophysical-union.csl
#+latex_header: \hypersetup{hidelinks}
#+latex_header: \usepackage{geometry}
#+latex_header: \geometry{margin=1in}

* Reason
:PROPERTIES:
:ID:
:CUSTOM_ID: h-4C24817F
:END:

Unidata is asking for a six month time extension to use our existing Jetstream2 allocation. Unidata needs the extension because we were not charged against our allocation until the Indiana University data center went fully operational on September 7, 2022, nearly halfway through our grant. As a result, we currently have unused resources we would like to continue using. Aside from the delay in being charged against our allocation, our rate of usage of Jetstream2 resources roughly matches our planned usage.

* Progress Report
:PROPERTIES:
:CUSTOM_ID: h-4895FCC8
:END:

** Summary
:PROPERTIES:
:CUSTOM_ID: h-1BF48B91
:END:

We are happy to report that we are making full use of the Unidata Jetstream2 allocation by continuing to provide vital computing resources to our community of university educators, instructors, and researchers as described in the original Jetstream2 allocation proposal.

** Customized JupyterHub Resources for Semester Classes
:PROPERTIES:
:CUSTOM_ID: h-96210E0E
:END:

Unidata is employing our Jetstream2 resource allocation for the benefit of students in the atmospheric science community by providing access to customized JupyterHub servers at an accelerating pace. The Jetstream2 allocation is also an integral part of the Unidata Science Gateway project. Since the launch of Jetstream2, we have deployed PyAOS (Python for the Atmospheric and Oceanic Sciences) JupyterHub installations at ten universities. Unidata tailors these servers to the requirements of the instructors so they can accomplish their Earth Systems Science teaching objectives. 152 students have used Unidata JupyterHub servers running on Jetstream2 in this manner.

** American Meteorological Society 2023 Meeting
:PROPERTIES:
:CUSTOM_ID: h-B86AC45B
:END:

*** Workshops
:PROPERTIES:
:CUSTOM_ID: h-F334802B
:END:

Unidata's use of Jetstream2 was crucial during the American Meteorological Society (AMS) 2023 meeting, where we supported three workshops with customized PyAOS JupyterHub servers: MetPy Short Course, Student Python Workshop, and the Colorado State University LROSE radar meteorology workshop. In all, Unidata had 141 participants using Jetstream2 resources at AMS 2023.

*** Presentation
:PROPERTIES:
:CUSTOM_ID: h-818FB3E4
:END:

Unidata delivered a presentation entitled "Unidata Science Gateway: Past, Present, and Future Plans" detailing our collaboration and use of the Jetstream and Jetstream2 projects since 2015 [cite:@Chastang2023a].

** Andrea Zonca Collaboration
:PROPERTIES:
:CUSTOM_ID: h-EC1F4212
:END:

Unidata staff continues to collaborate with Andrea Zonca (SDSC/Jetstream2) employing his port of the "Zero to JupyterHub with Kubernetes"[fn:1] project to OpenStack and Jetstream2 [cite:@Zonca2017a] [cite:@Zonca2018a]. We give Andrea feedback by testing his instructional blog entries and workflows[fn:2]. When we encounter issues, we submit bug reports via GitHub and work together until the problem is resolved.
Notably, we worked with Andrea to provide our users with a shared directory that can be accessed from all user JupyterLab environments. [fn:3] This has been a long-standing feature request that we were excited to finally deliver.

** Weather Research Forecast Model on Jetstream2
:PROPERTIES:
:CUSTOM_ID: h-45CAE6B3
:END:

*** Summary

For the first time in Unidata's presence on Jetstream, we have deployed a containerized version of the Weather Research Forecast (WRF) numerical weather prediction system on Jetstream2, providing two different scenarios. This new capability allows for exploration of Numerical Weather Prediction (NWP) models and subsequent analysis and visualization of the output in a data-proximate manner, for example, in a JupyterLab environment.

*** WRF Navajo Technical University

Unidata is collaborating with the Southwestern Indian Polytechnic Institute and Navajo Technical University to deploy an operational WRF model over the Navajo Nation. This project aims to provide Tribal Nations, and the Tribal Colleges and Universities (TCUs) with the capacity for environmental monitoring in alignment with data sovereignty objectives[cite:@Espinoza2022a] [cite:@Weber2023a].

*** WRF Single Column Model in JupyterHub

In collaboration with Greg Blumberg at Millersville University, Unidata staff have deployed a single-column WRF model in a JupyterHub environment for undergraduate instructional objectives.

** GPU Experimentation
:PROPERTIES:
:CUSTOM_ID: h-133EBF8B
:END:

Unidata staff have started experimenting with Jetstream2 GPU hardware. In particular, we have deployed a GPU-enabled JupyterHub equipped with Tensorflow and Pytorch software, and are evaluating its capabilities specifically with regard to educational settings. We are also currently working on testing out Andrea Zonca's GPU version of deploying a "JupyterHub with Kubernetes" cluster [fn:4].

** Unidata Science Gateway Reimagined Project
:PROPERTIES:
:CUSTOM_ID: h-1AA6281E
:END:

The Unidata Science Gateway unites Unidata technologies with Jetstream2 and open-source software such as Project Jupyter to provide the academic and research community an environment they can use to access, analyze, and visualize real-time and case study Earth Systems Science data. While the Unidata Science Gateway has been moderately successful in reaching our audience, we would like to improve and expand our web presence, building a portal that allows users to more easily access educational, computing, and data resources. We aim to revamp our current gateway interface to become a more dynamic hub for education, data access, and research. We presented our vision and mission statement in a poster presentation at the Gateways 2022 conference [cite:@Chastang2022b]. Unidata staff are currently in the design phase of this project.

** AWIPS
:PROPERTIES:
:CUSTOM_ID: h-240CF4A9
:END:

Unidata continues to host publicly accessible AWIPS EDEX servers on the Jetstream2 cloud platform, where we serve real-time meteorological and geographic data to AWIPS CAVE clients[cite:@Meyer2023a]. Our EDEX servers are also accessible via python-awips, which is a data access framework (DAF) API. The distributed architectural concepts of AWIPS allow us to scale EDEX in the cloud to account for the desired data feed (and size). We continue using Jetstream2 to develop cloud-deployable AWIPS instances as virtual machines images (VMI) available to users of OpenStack CLI.

Unidata AWIPS development staff are mainly employing Jetstream2 "CPU Instances" (11 VMs mostly of various large flavors) for the current EDEX configuration. We have also been experimenting deploying EDEX with Jetstream2 "Large Memory Instances."

** References
:PROPERTIES:
:CUSTOM_ID: h-88CC8E0F
:END:

#+print_bibliography:

** Footnotes
:PROPERTIES:
:CUSTOM_ID: h-7D74C60F
:END:

[fn:1] https://z2jh.jupyter.org
[fn:2] https://www.zonca.dev/
[fn:3] https://www.zonca.dev/posts/2023-02-06-nfs-server-kubernetes-jetstream
[fn:4] https://www.zonca.dev/posts/2023-01-23-kubernetes-gpu-jetstream2
