#+title: Supplement Request: Next Phase of Unidata Cloud-hosted Data Services: Transitioning and Expanding Operations to Jetstream2 and Investigating New Hardware Capabilities
#+author: Mohan Ramamurthy (PI), Julien Chastang (co-I), Ana Espinoza

#+bibliography: jetstream.bib

#+options: toc:nil num:t date:nil author:nil auto-id:t
#+startup: content

#+begin_src emacs-lisp :results silent :exports none
  ;; https://list.orgmode.org/CAOWRwxAk-B8bqFry9r6ibBi-5L29yrCuhHxhjCRmaKLwhsuHcA@mail.gmail.com/#r
  (require 'oc-csl)
  (setq org-cite-export-processors
        '((t csl "~/git/science-gateway/.org/proposals/2022/jetstream2-xsede-research/american-geophysical-union.csl")
          ))
#+end_src

#+latex_header: \hypersetup{hidelinks}
#+latex_header: \usepackage{geometry}
#+latex_header: \geometry{margin=1in}

* Reason
:PROPERTIES:
:CUSTOM_ID: h-6D810E31
:END:

The Unidata Program Center is requesting a Jetstream2 cloud computing supplement of 2,000,000 additional Service Units (SUs) to address higher than anticipated demand from our PyAOS JupyterHub clusters, which have supported 284 students across 11 academic institutions since the beginning of the year. This supplement is also crucial for expanding our EDEX VMs to meet the growing needs of the AWIPS community while ensuring uninterrupted use of other existing services such as THREDDS and RAMADDA. Furthermore, it will accommodate the increased demand for our JupyterHub clusters during the busy summer workshop and internship season, including support for the 2023 Unidata Users Workshop, which has attracted participants from across Earth Systems Science domains. By providing ample resources, this supplement will facilitate a smooth start to the fall semester for university users of Unidata-configured PyAOS JupyterHub clusters. Ultimately, this supplement is essential for maintaining the quality and continuity of Unidata services until October 1, thereby promoting scientific education and collaboration within the atmospheric and related sciences community.

* Progress Report
:PROPERTIES:
:CUSTOM_ID: h-3C183B75
:END:

** Summary
:PROPERTIES:
:CUSTOM_ID: h-25C94010
:END:

In alignment with the objectives outlined in our original Jetstream2 allocation proposal, we are pleased to report that Unidata is successfully making use of allocated resources (CPU, GPU, and large instances) to their fullest capacity. This Jetstream2 grant has enabled us to provide essential computing capacity to our community of university educators, instructors, and researchers.

** Customized JupyterHub Resources for Semester Classes
:PROPERTIES:
:CUSTOM_ID: h-018F39CE
:END:

Unidata is employing our Jetstream2 resource allocation for the benefit of students in the atmospheric science community by providing access to customized JupyterHub servers at an accelerating pace. Since the launch of Jetstream2, we have deployed PyAOS (Python for the Atmospheric and Oceanic Sciences) JupyterHub installations at 12 universities. Unidata tailors these servers to the requirements of the instructors so they can accomplish their Earth Systems Science teaching objectives. 352 students have used Unidata JupyterHub servers running on Jetstream2 in this manner.

** American Meteorological Society 2023 Meeting
:PROPERTIES:
:CUSTOM_ID: h-C3B5C2DD
:END:

*** Workshops
:PROPERTIES:
:CUSTOM_ID: h-3F1F3249
:END:

Unidata's use of Jetstream2 was crucial during the American Meteorological Society (AMS) 2023 meeting, where we supported three workshops with customized PyAOS JupyterHub servers: MetPy Short Course, Student Python Workshop, and the Colorado State University LROSE radar meteorology workshop. In all, Unidata had 141 participants using Jetstream2 resources at AMS 2023.

*** Presentation
:PROPERTIES:
:CUSTOM_ID: h-F927758D
:END:

Unidata delivered a presentation entitled "Unidata Science Gateway: Past, Present, and Future Plans" detailing our collaboration and use of the Jetstream and Jetstream2 projects since 2015 [cite:@Chastang2023a].

**  European Geosciences Union 2023 Meeting
:PROPERTIES:
:CUSTOM_ID: h-7C3B4549
:END:

Unidata delivered a presentation entitled "Unidata Science Gateway: A research infrastructure to advance research and education in the Earth System Sciences" [cite:@Ramamurthy2023a].

** Andrea Zonca Collaboration
:PROPERTIES:
:CUSTOM_ID: h-1CFFA048
:END:

Unidata staff continues to collaborate with Andrea Zonca (SDSC/Jetstream2) employing his port of the "Zero to JupyterHub with Kubernetes"[fn:1] project to OpenStack and Jetstream2 [cite:@Zonca2017a] [cite:@Zonca2018a]. We give Andrea feedback by testing his instructional blog entries and workflows[fn:2]. When we encounter issues, we submit bug reports via GitHub and work together until the problem is resolved. Notably, we worked with Andrea to provide our users with a shared directory that can be accessed from all user JupyterLab environments. [fn:3] This has been a long-standing feature request that we were excited to finally deliver.

** Weather Research Forecast Model on Jetstream2
:PROPERTIES:
:CUSTOM_ID: h-DBC458B4
:END:

*** Summary
:PROPERTIES:
:CUSTOM_ID: h-1E46F784
:END:

For the first time in Unidata's presence on Jetstream, we have deployed a containerized version of the Weather Research Forecast (WRF) numerical weather prediction system on Jetstream2, providing two different scenarios. This new capability allows for exploration of Numerical Weather Prediction (NWP) models and subsequent analysis and visualization of the output in a data-proximate manner, for example, in a JupyterLab environment.

*** WRF Navajo Technical University
:PROPERTIES:
:CUSTOM_ID: h-DE3E64DA
:END:

Unidata is collaborating with the Southwestern Indian Polytechnic Institute and Navajo Technical University to deploy an operational WRF model over the Navajo Nation. This project aims to provide Tribal Nations, and the Tribal Colleges and Universities (TCUs) with the capacity for environmental monitoring in alignment with data sovereignty objectives [cite:@Espinoza2022a] [cite:@Weber2023a].

*** WRF Single Column Model in JupyterHub
:PROPERTIES:
:CUSTOM_ID: h-BE6D1C50
:END:

In collaboration with Greg Blumberg at Millersville University, Unidata staff have deployed a single-column WRF model in a JupyterHub environment for undergraduate instructional objectives.

** GPU Experimentation
:PROPERTIES:
:CUSTOM_ID: h-D72054A5
:END:

Unidata staff have started experimenting with Jetstream2 GPU hardware to explore areas such as advanced deep learning applied to Earth System Science. With the assistance [fn:4] of Andrea Zonca, we have deployed a GPU-enabled JupyterHub currently hosted at https://jupyterhub.unidata.ucar.edu equipped with TensorFlow and PyTorch software as well as geoscience notebooks that employ this specialized hardware, and are evaluating its capabilities specifically with regard to educational settings.

** Unidata Science Gateway Reimagined Project
:PROPERTIES:
:CUSTOM_ID: h-D5E44DED
:END:

The Unidata Science Gateway unites Unidata technologies with Jetstream2 and open-source software such as Project Jupyter to provide the academic and research community an environment they can use to access, analyze, and visualize real-time and case study Earth Systems Science data. While the Unidata Science Gateway has been moderately successful in reaching our audience, we would like to improve and expand our web presence, building a portal that allows users to more easily access educational, computing, and data resources. We aim to revamp our current gateway interface to become a more dynamic hub for education, data access, and research. We presented our vision and mission statement in a poster presentation at the Gateways 2022 conference [cite:@Chastang2022b]. Unidata staff are currently in the design phase of this project.

** AWIPS
:PROPERTIES:
:CUSTOM_ID: h-B9DF4CCE
:END:

Unidata continues to host publicly accessible AWIPS EDEX servers on the Jetstream2 cloud platform, where we serve real-time meteorological and geographic data to AWIPS CAVE clients [cite:@Meyer2023a]. Our EDEX servers are also accessible via python-awips, which is a data access framework (DAF) API. The distributed architectural concepts of AWIPS allow us to scale EDEX in the cloud to account for the desired data feed (and size). We continue using Jetstream2 to develop cloud-deployable AWIPS instances as virtual machines images (VMI) available to users of OpenStack CLI.

Unidata AWIPS development staff are mainly employing Jetstream2 "CPU Instances" (11 VMs mostly of various large flavors) for the current EDEX configuration. We have also been experimenting deploying EDEX with Jetstream2 "Large Memory Instances."

** References
:PROPERTIES:
:CUSTOM_ID: h-447E009A
:END:

#+print_bibliography:

** Footnotes
:PROPERTIES:
:CUSTOM_ID: h-F4471B56
:END:

[fn:1] https://z2jh.jupyter.org
[fn:2] https://www.zonca.dev/
[fn:3] https://www.zonca.dev/posts/2023-02-06-nfs-server-kubernetes-jetstream
[fn:4] https://www.zonca.dev/posts/2023-01-23-kubernetes-gpu-jetstream2
