#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t

#+TITLE: Unidata Science Gateway News
#+DATE: {{{time(%Y-%m-%d %H:%M:%S %Z)}}}
#+AUTHOR: Julien Chastang
#+EMAIL: chastang at ucar dot edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.2 (Org mode 9.2.1)

#+HTML_LINK_HOME: https://science-gateway.unidata.ucar.edu/
#+RSS_IMAGE_URL: https://avatars2.githubusercontent.com/u/613345?s=200&amp;v=4

* 12/07/2021, Unidata Science Gateway at AGU and AMS
  :PROPERTIES:
   :RSS_TITLE: Unidata Science Gateway at AGU and AMS
   :PUBDATE: <2021-12-07 Tue>
   :RSS_PERMALINK: index.html#h-FF27A203
   :CUSTOM_ID: h-FF27A203
   :ID:       FAFE1202-4F17-4ABA-AB0D-EBC76E5D475C
  :END:

During the months of December and January there will be two presentations that touch upon the Unidata Science Gateway. There will be a lightning talk entitled "[[https://agu.confex.com/agu/fm21/meetingapp.cgi/Paper/967436][The use of the Unidata Science Gateway as a cyberinfrastructure resource to facilitate education and research during COVID-19]]" at the American Geophysical Union Fall 2021 meeting. In January there will be a talk called "[[https://ams.confex.com/ams/102ANNUAL/meetingapp.cgi/Paper/398651][Unidata Partners with UCAR SOARS Program to Help Protégés and Their Mentors with Atmospheric Science Internships]]" at the American Meteorological Society's 2022 winter meeting.

* 9/24/2021, Unidata Community Survey
  :PROPERTIES:
   :RSS_TITLE: Unidata Community Survey
   :PUBDATE: <2021-09-24 Fri>
   :RSS_PERMALINK: index.html#h-F4EE3A44
   :CUSTOM_ID: h-F4EE3A44
   :ID:       EF0BE0BF-DAD5-4D1F-9441-45265A9C8DB8
  :END:

Make your voice heard on Unidata Science Gateway offerings. Please partake in the [[https://bit.ly/2021UnidataSurvey][Unidata Community Survey]].

* 9/17/2021, Unidata Science Gateway Presentation at eScience 2021
  :PROPERTIES:
   :RSS_TITLE: Unidata Science Gateway Presentation at eScience 2021
   :PUBDATE: <2021-09-17 Fri>
   :RSS_PERMALINK: index.html#h-81EC6CA6
   :CUSTOM_ID: h-81EC6CA6
   :ID:       CBF7EEF9-D093-4E99-A093-CE2BF78E9ECB
  :END:

The presentation will be given as part of the 17th IEEE eScience 2021 International Conference. [[https://www.escience2021.org/timetable][The talk is part of the Technical Program and will be delivered on Wednesday, September 22nd at 15:30-1600 CEST]].

