#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t

#+TITLE: Unidata Science Gateway News
#+DATE: {{{time(%Y-%m-%d %H:%M:%S %Z)}}}
#+AUTHOR: Julien Chastang
#+EMAIL: chastang at ucar dot edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.2 (Org mode 9.2.1)

#+HTML_LINK_HOME: https://science-gateway.unidata.ucar.edu/
#+RSS_IMAGE_URL: https://avatars2.githubusercontent.com/u/613345?s=200&amp;v=4

* 05/20/2022, Unidata Science Gateway Talk at EGU
  :PROPERTIES:
  :RSS_TITLE: Unidata Science Gateway Talk at EGU
  :PUBDATE: <2022-05-20 Fri>
  :RSS_PERMALINK: index.html#h-642E7F66
  :CUSTOM_ID: h-642E7F66
  :ID:       2D590004-6AE6-4BDC-AB6D-35EB6B86A25F
  :END:

Unidata Director, Mohan Ramamurthy, will be speaking at the European Geosciences Union on Monday, May 23 giving a talk entitled "[[https://meetingorganizer.copernicus.org/EGU22/session/42416][The use of the Unidata Science Gateway as a cyberinfrastructure resource to facilitate education and research during COVID-19]]".

* 04/29/2022, Mini Gateways 2022 Video
  :PROPERTIES:
  :RSS_TITLE: Mini Gateways 2022 Video
  :PUBDATE: <2022-04-29 Fri>
  :RSS_PERMALINK: index.html#h-0A6F9597
  :CUSTOM_ID: h-0A6F9597
  :ID:       F2F8F02C-AA6C-4367-9028-AB55633CE5B8
  :END:

My colleague, Andrea Zonca, [[https://zonca.dev/2022/04/science-gateway-dask-zarr.html][has posted a video]] of our presentation at the SGCI Mini Gateways 2022 online conference.

* 12/07/2021, Unidata Science Gateway at AGU and AMS
  :PROPERTIES:
   :RSS_TITLE: Unidata Science Gateway at AGU and AMS
   :PUBDATE: <2021-12-07 Tue>
   :RSS_PERMALINK: index.html#h-FF27A203
   :CUSTOM_ID: h-FF27A203
   :ID:       FAFE1202-4F17-4ABA-AB0D-EBC76E5D475C
  :END:

During the months of December and January there will be two presentations that touch upon the Unidata Science Gateway. There will be a lightning talk entitled "[[https://agu.confex.com/agu/fm21/meetingapp.cgi/Paper/967436][The use of the Unidata Science Gateway as a cyberinfrastructure resource to facilitate education and research during COVID-19]]" at the American Geophysical Union Fall 2021 meeting. In January there will be a talk called "[[https://ams.confex.com/ams/102ANNUAL/meetingapp.cgi/Paper/398651][Unidata Partners with UCAR SOARS Program to Help Protégés and Their Mentors with Atmospheric Science Internships]]" at the American Meteorological Society's 2022 winter meeting.

