#+title: Progress Report

#+bibliography: jetstream.bib

#+options: toc:nil num:t date:nil author:nil auto-id:t
#+startup: content

#+cite_export: csl ieee.csl

#+latex_class: article

#+latex_header: \hypersetup{hidelinks}
#+latex_header: \usepackage{geometry}
#+latex_header: \geometry{top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm}
#+latex_header: \usepackage{mathptmx}
#+latex_header: \usepackage{wrapfig}
#+latex_header: \usepackage{graphicx}

* Summary
:PROPERTIES:
:CUSTOM_ID: h-59B1064F
:END:

TODO

* Customized JupyterHub Resources for Atmospheric Science Education
:PROPERTIES:
:CUSTOM_ID: h-BAE2B39B
:END:

NSF Unidata is using its Jetstream2 resource allocation to support atmospheric science education by providing customized PyAOS (Python for Atmosphere and Ocean Science) JupyterHub servers [cite:@Arms2020b]. NSF Unidata staff tailors these cloud-based environments to the instructional requirements of individual university courses, enabling instructors to meet their Earth system science teaching objectives. During the reporting period, NSF Unidata served 430 students at 12 academic institutions and workshops on NSF Unidata JupyterHub servers running on Jetstream2 [cite:@unidatastatus2026].

A notable advancement during the past year has been the integration of streaming cloud desktop technology that provides browser-based access to the Unidata Integrated Data Viewer (IDV) and the Advanced Weather Interactive Processing System (AWIPS) Common AWIPS Visualization Environment (CAVE), the operational weather visualization workstation used by National Weather Service (NWS) forecast offices[cite:@Chastang2025bPaper] [cite:@Chastang2025bSlides] [cite:@Chastang2026a]. This approach makes sophisticated desktop visualization software available to students without requiring local installation or high-performance hardware. During the fall 2025 semester, Professor Brian Mapes (University of Miami) successfully incorporated the IDV streaming desktop capability into a graduate-level atmospheric science course. Students used a Jupyter notebook to compute Global Forecast System (GFS) derived wind fields with WindsPharm, a Python package for atmospheric wind analysis, and wrote the results to netCDF, a self-describing scientific data format developed by Unidata. These results were then visualized in the IDV alongside infrared satellite imagery, all within a single integrated cloud environment. Students performed the complete workflow, from numerical analysis in a Jupyter notebook to interactive visualization in IDV, without leaving the browser.

* Kubespray to Magnum Migration
:PROPERTIES:
:CUSTOM_ID: h-662CAE73
:END:

** Magnum Transition
:PROPERTIES:
:CUSTOM_ID: h-CE3BC665
:END:

During this reporting period, the NSF Unidata science gateway team transitioned its customized PyAOS JupyterHub deployments to Jetstream2's Magnum service which provides OpenStack managed Kubernetes clusters with built-in autoscaling. NSF Unidata employs the "JupyterHub with Kubernetes" project to deploy these environments. For the past several years, our Kubernetes clusters had been provisioned with Kubespray, Terraform and Ansible [cite:@Zonca2018a]. Because these clusters had to be sized for peak anticipated demand, computing resources were underutilized during quieter periods such as outside classroom times. With Magnum's autoscaling capabilities [cite:@zonca2024magnum], clusters now expand and contract automatically in response to actual usage thereby dramatically improving resource utilization while still supporting peak workloads.

** NSF Unidata and Jetstream2 Collaboration
:PROPERTIES:
:CUSTOM_ID: h-F7A3F9E0
:END:

Over the course of this work, NSF Unidata deployed 19 OpenStack Magnum clusters, along with additional test clusters to support JupyterHub environments for university courses and workshops. Operating Magnum at this scale has allowed NSF Unidata to gain operational knowhow with the service. This experience has enabled us to identify a number of issues and to work closely with the Jetstream2 team to improve Magnum for the broader community.

Through this collaboration, the NSF Unidata Science gateway team helped identify and resolve a number of issues affecting OpenStack Magnum deployments on Jetstream2. These contributions included testing and validating the migration of NGINX ingress controller to Traefik, investigating Magnum cluster lifecycle issues (including cluster creation, delete and persistent volume cleanup), identifying and helping resolve security vulnerabilities, adopting a shared NSF home directory architecture based on the 2i2c JupyterHub model, and working with Jetstream2 staff to import support for GPU-enabled and Dask-enabled JupyterHub deployments. In sum, these improvements attained through this collaboration have increased the reliability and security of Magnum on Jestream2.
-

* References
:PROPERTIES:
:CUSTOM_ID: h-1DB3A62A
:END:

\setlength{\parindent}{0pt}

#+print_bibliography:

* Footnotes
:PROPERTIES:
:CUSTOM_ID: h-A67808EB
:END:

[fn:1]https://github.com/Unidata/MLscratchpad/tree/main/aiNWP

