#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t
#+TITLE: Creating a RAMADDA VM on Jetstream
#+DATE: <2017-03-17 Fri>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)
#+STARTUP: content

#+PROPERTY: header-args :eval no :tangle no

* Creating a RAMADDA VM on Jetstream
  :PROPERTIES:
  :CUSTOM_ID: h-07FD791D
  :END:
** Create a RAMADDA VM on Jetstream
   :PROPERTIES:
   :CUSTOM_ID: h-F4023EC5
   :END:

Create an ~m1.medium~ VM with the [[file:../../openstack/readme.org::#h-03303143][Jetstream OpenStack API]]. [[file:../../openstack/readme.org::#h-9BEEAB97][Create and attach]] a 100GB =/repository= volume to that VM. Work with Unidata system administrator staff to have this VM's IP address resolve to =ramadda.scigw.unidata.ucar.edu=.

** Clone the science-gateway Repository
   :PROPERTIES:
   :CUSTOM_ID: h-968FA51C
   :END:

We will be making heavy use of the ~Unidata/science-gateway~ git repository.

#+begin_src shell
  git clone https://github.com/Unidata/science-gateway
#+END_SRC

** Start RAMADDA With Docker and docker-compose
   :PROPERTIES:
   :CUSTOM_ID: h-2E18E909
   :END:

With the help of Docker and ~docker-compose~, starting a VM with the RAMADDA content management system should be fairly easy. There are a few directories you will need to map from outside to within the container. [[file:../../vm-init-readme.org::#h-786799C4][See here to install Docker and docker-compose]].

** /repository Directory
   :PROPERTIES:
   :CUSTOM_ID: h-2F1A5636
   :END:

The =/repository= directory should be a fairly beefy data volume (e.g., 100 GBs) or however much data you anticipate your RAMADDA users will consume. [[file:../../openstack/readme.org::#h-9BEEAB97][See here if creating data volumes via the JetStream OpenStack API]].

** Create RAMADDA default password
   :PROPERTIES:
   :CUSTOM_ID: h-D5095E2A
   :END:

[[#h-224A9684][When starting RAMADDA for the first time]], you must have  a =password.properties= file in the RAMADDA home directory which is =/repository/=. See [[https://ramadda.org//repository/userguide/toc.html][RAMADDA documentation]] for more details on setting up RAMADDA. Here is a =pw.properties= file to get you going. Change password below to something more secure!

#+begin_src shell :tangle ../../../vms/ramadda/ramadda-install.sh :shebang "#!/bin/bash"
  # Create RAMADDA default password

  echo ramadda.install.password=changeme! | tee --append \
    /repository/pw.properties > /dev/null
#+END_SRC

** RAMADDA log Directories
   :PROPERTIES:
   :CUSTOM_ID: h-1C3FF741
   :END:

*** Create log Directories
    :PROPERTIES:
    :CUSTOM_ID: h-DABCF6E2
    :END:

You will need an Apache Tomcat and RAMADDA log directories:

#+begin_src shell :tangle ../../../vms/ramadda/ramadda-install.sh
   mkdir -p /logs/ramadda-tomcat/
   mkdir -p /logs/ramadda/
 #+END_SRC

** LDM Data Directory from idd-archiver Via NFS
   :PROPERTIES:
   :CUSTOM_ID: h-85431E50
   :END:

If you plan on employing the [[https://ramadda.org//repository/userguide/developer/filesystem.html][server-side view capability of RAMADDA]] which is quite useful for monitoring your LDM data feeds, you will have to make that directory (e.g., =/data/ldm/=) available to the RAMADDA VM and Docker container. In our present configuration, that directory is on the ~idd-archiver~ machine so you need to mount it via NFS on the ~10.0.~ network. For example, if ~idd-archiver~ is at ~10.0.0.4~:

#+begin_src shell
  # create the NFS mount point
  sudo mkdir -p /data
  sudo mount 10.0.0.4:/data /data
#+END_SRC

** HTTPS and SSL Certificate
   :PROPERTIES:
   :CUSTOM_ID: h-44DE4A34
   :END:
*** Certificate from CA
    :PROPERTIES:
    :CUSTOM_ID: h-5B0B20B7
    :END:

 [[https://github.com/Unidata/tomcat-docker#h-E0520F81][See the parent Tomcat container for instructions on HTTPS]].

** Ensure /repository and /data Availability Upon Machine Restart
   :PROPERTIES:
   :CUSTOM_ID: h-6423976C
   :END:

[[file:../../openstack/readme.org::#h-9BEEAB97][Ensure the =/repository= volume availability upon machine restart]].

#+begin_src shell
  sudo echo UUID=2c571c6b-c190-49bb-b13f-392e984a4f7e	 /repository	ext4	defaults	1	 1 | tee --append /etc/fstab > /dev/null
#+END_SRC

*** /data NFS Mounted Volume
    :PROPERTIES:
    :CUSTOM_ID: h-286B798E
    :END:

In addition, you will want to ensure the NFS =/data= volume is also available with the help of =fstab=.

#+begin_src shell
  sudo echo 10.0.0.4:/data    /data   nfs rsize=32768,wsize=32768,timeo=14,intr | tee --append /etc/fstab > /dev/null
#+END_SRC

** Port 80
   :PROPERTIES:
   :CUSTOM_ID: h-404D9595
   :END:

[[file:../../openstack/readme.org::#h-D6B1D4C2][Open ports]]  ~80~ and ~443~ on the RAMADDA VM via OpenStack. Port ~80~ and ~443~ requests will be forwarded to ~8080~ and ~8443~ inside the RAMADDA Docker container, respectively.

** docker-compose.yml
   :PROPERTIES:
   :CUSTOM_ID: h-7E683535
   :END:

Based on the directory set we have defined, the =docker-compose.yml= file will look something like:

#+INCLUDE: "../../../vms/ramadda/docker-compose.yml" src yaml

*** RAMADDA Environment Variable Parameterization
    :PROPERTIES:
    :CUSTOM_ID: h-704211AA
    :END:

You can provide additional RAMADDA parameterization via the =compose.env= file referenced in the =docker-compose.yml= file.

#+INCLUDE: "../../../vms/ramadda/compose.env" src shell

** SSL
   :PROPERTIES:
   :CUSTOM_ID: h-4DC08484
   :END:

We are moving towards an HTTPS only world. As such, you'll want to run a [[https://github.com/Unidata/tomcat-docker#h-E0520F81][RAMADDA production server on HTTPS]]. [[#h-224A9684][Once RAMADDA is running]], you'll want to configure RAMADDA for SSL via the administrative account. There is documentation about this topic [[http://ramadda.org/repository/userguide/installing.html#ssl][here]]. The main thing appears to be the Admin → Settings → Site and Contact Information, ensure "Force all connections to be secure" is checked. The ~repository.properties~ file that is referenced in the ~docker-compose.yml~ should be configured properly for SSL.

** Start RAMADDA
   :PROPERTIES:
   :CUSTOM_ID: h-224A9684
   :END:

Once you have done the work of setting up RAMADDA related directories in the way you like,

#+begin_src shell
  docker-compose up -d
#+END_SRC

to start RAMADDA.
** Navigate to RAMADDA
   :PROPERTIES:
   :CUSTOM_ID: h-81FED1EC
   :END:

In a web browser, navigate to [[https://ramadda.scigw.unidata.ucar.edu/repository][https://ramadda.scigw.unidata.ucar.edu/repository]]. If this is the first time you are accessing RAMADDA, RAMADDA will guide you through a server configuration workflow. You will be prompted for the repository password [[#h-D5095E2A][you defined earlier]].
** Access RAMADDA with the Unidata IDV
   :PROPERTIES:
   :CUSTOM_ID: h-73BB6227
   :END:

RAMADDA has good integration with the [[http://www.unidata.ucar.edu/software/idv/][Unidata Integrated Data Viewer (IDV)]] and the two technologies work well together.

*** RAMADDA IDV Plugin
    :PROPERTIES:
    :CUSTOM_ID: h-3CCEFC0F
    :END:

IDV users may wish to install the [[http://www.unidata.ucar.edu/software/idv/docs/workshop/savingstate/Ramadda.html][RAMADDA IDV plugin]] to publish IDV bundles to RAMADDA.

*** RAMADDA Server Side Views
    :PROPERTIES:
    :CUSTOM_ID: h-C8481694
    :END:

RAMADDA also has access to the LDM =/data/= directory so you may want to set up [[https://ramadda.org//repository/userguide/developer/filesystem.html][server-side view of this part of the file system]]. This is a two step process where administrators go to the Admin, Access, File Access menu item and lists the allowed directories they potentially wish to expose via RAMADDA. Second, the users are now capable of creating a "Server Side" Files with the usual RAMADDA entry creation mechanisms.

*** RAMADDA Catalog Views from the IDV
    :PROPERTIES:
    :CUSTOM_ID: h-589449E2
    :END:

Finally, you can enter this catalog URL in the IDV dashboard to examine data holdings shared bundles, etc. on RAMADDA. For example, [[https://ramadda.scigw.unidata.ucar.edu/repository?output=thredds.catalog]].
