name: vt-spring-2023
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alabaster
  - appdirs
  - arrow
  - astroid
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - beautifulsoup4
  - binaryornot
  - black
  - blas
  - bleach
  - bokeh
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - cdsapi
  - certifi
  - cf_xarray
  - cffi
  - cftime
  - chardet
  - charset-normalizer
  - click
  - cloudpickle
  - cmaps
  - colorama
  - cookiecutter
  - cryptography
  - curl
  - cycler
  - cytoolz
  - dask
  - dask-core
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - diff-match-patch
  - dill
  - distributed
  - docutils
  - entrypoints
  - eofs
  - expat
  - fftw
  - flake8
  - fontconfig
  - fonttools
  - freeglut
  - freetype
  - fsspec
  - geocat-comp
  - geocat-f2py
  - geocat-viz
  - geos
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - heapdict
  - icu
  - idna
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - inflection
  - intel-openmp
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - isort
  - jasper
  - jedi
  - jeepney
  - jellyfish
  - jinja2
  - jinja2-time
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglu
  - libgomp
  - libllvm10
  - libnetcdf
  - libnghttp2
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - locket
  - lz4
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - metpy
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msgpack-python
  - munkres
  - mypy_extensions
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - netcdf4
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - partd
  - pathspec
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pint
  - pip
  - platformdirs
  - pluggy
  - ply
  - pooch
  - poyo
  - proj
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pycodestyle
  - pycparser
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pyls-spyder
  - pymannkendall
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyqtwebengine
  - pyrsistent
  - pyshp
  - pysocks
  - python=3.10
  - python-dateutil
  - python-fastjsonschema
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-server
  - python-slugify
  - python_abi
  - pytz
  - pyxdg
  - pyzmq
  - qdarkstyle
  - qstylizer
  - qt-main
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtpy
  - qtwebkit
  - readline
  - requests
  - rope
  - rtree
  - scikit-learn
  - scipy
  - seaborn
  - secretstorage
  - setuptools
  - shapely
  - sip
  - six
  - snowballstemmer
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlite
  - tblib
  - testpath
  - text-unidecode
  - textdistance
  - threadpoolctl
  - three-merge
  - tinycss
  - tk
  - toml
  - tomli
  - tomlkit
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - ujson
  - unidecode
  - urllib3
  - watchdog
  - wcwidth
  - webencodings
  - whatthepatch
  - wheel
  - wrapt
  - wurlitzer
  - xarray
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libx11
  - xorg-libxau
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - yapf
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
  - siphon
  - geopandas
  - geopy
  - pip:
    - eccodes
    - findlibs
    - pyqt5-sip
    - pyyaml
