version: '3'

services:

  ramadda:
    image: unidata/ramadda-docker:latest
    container_name: ramadda
    # restart: always
    ports:
      - "80:8080"
    volumes:
      - /repository/:/data/repository/
      - /data/ldm/:/data/ldm/
      - ~/logs/ramadda-tomcat/:/usr/local/tomcat/logs/
      - ~/logs/ramadda/:/data/repository/logs/
    env_file:
      - "compose.env"
