name: ncarml-spring-2025
channels:
  - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - cartopy
  - ipywidgets
  - keras
  - matplotlib
  - metpy
  - numpy
  - pandas
  - pip
  - pyarrow
  - python-awips
  - scikit-learn
  - seaborn
  - siphon
  - xarray
  - xgboost
  - pip:
      - catboost
      - palmerpenguins
