#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+OPTIONS: auto-id:t
#+TITLE: Creating an ADDE VM on Jetstream
#+DATE: <2017-06-14 Wed>
#+AUTHOR: Julien Chastang
#+EMAIL: chastang@ucar.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.2 (Org mode 9.0.5)
#+STARTUP: content

#+PROPERTY: header-args :eval no :tangle no

* Creating an ADDE VM on Jetstream
  :PROPERTIES:
  :CUSTOM_ID: h-E8DA29EC
  :END:
** Create an ADDE VM on Jetstream
   :PROPERTIES:
   :CUSTOM_ID: h-10109CCE
   :END:

Create an ~m1.medium~ VM with the [[file:../../openstack/readme.org::#h-03303143][Jetstream OpenStack API]]. Work with Unidata system administrator staff to have this VM's IP address resolve to =adde.scigw.unidata.ucar.edu=.

** Clone the science-gateway Repository
   :PROPERTIES:
   :CUSTOM_ID: h-E6D3D21F
   :END:

We will be making heavy use of the ~Unidata/science-gateway~ git repository.

#+BEGIN_SRC shell
  git clone https://github.com/Unidata/science-gateway
#+END_SRC

** Start ADDE With Docker and docker-compose
   :PROPERTIES:
   :CUSTOM_ID: h-0897ADA4
   :END:

With the help of Docker and ~docker-compose~, starting a VM with an ADDE server should be fairly easy. There are a few directories you will need to map from outside to within the container.  [[file:../../vm-init-readme.org::#h-786799C4][See here to install Docker and docker-compose]].

** ADDE Configuration
   :PROPERTIES:
   :CUSTOM_ID: h-C9A644E9
   :END:

A minor amount of configuration is required to get ADDE going.

#+BEGIN_SRC shell :tangle ../../../vms/mcidas/mcidas-install.sh :shebang "#!/bin/bash"
  mkdir -p ~/etc ~/mcidas/upcworkdata/ ~/mcidas/decoders/ ~/mcidas/util/
  cp pqact.conf_mcidasA ~/etc
  cp RESOLV.SRV ~/mcidas/upcworkdata/
#+END_SRC

** LDM Data Directory from idd-archiver Via NFS
   :PROPERTIES:
   :CUSTOM_ID: h-D58FB64C
   :END:

ADDE will need access to the =/data/ldm/= directory from ~idd-archiver~ in order to serve data. Mount it via NFS on the ~10.0.~ network. For example, if ~idd-archiver~ is at ~10.0.0.4~:

#+BEGIN_SRC shell :exports none :tangle ../../../vms/mcidas/nfs-install.sh :shebang "#!/bin/bash"
  if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
  fi
#+END_SRC

#+BEGIN_SRC shell :tangle ../../../vms/mcidas/nfs-install.sh
  # create the NFS mount point
  mkdir -p /data
  mount 10.0.0.4:/data /data
#+END_SRC

*** Ensure /data Availability Upon Machine Restart
    :PROPERTIES:
    :CUSTOM_ID: h-C586CD26
    :END:

You will want to ensure the NFS =/data= volume is available with the help of =fstab=.

#+BEGIN_SRC shell :tangle ../../../vms/mcidas/nfs-install.sh
  echo 10.0.0.4:/data    /data   nfs rsize=32768,wsize=32768,timeo=14,intr | tee --append /etc/fstab > /dev/null
#+END_SRC

** Port 112
   :PROPERTIES:
   :CUSTOM_ID: h-3E2295A4
   :END:

ADDE operates via port ~112~. [[file:../../openstack/readme.org::#h-D6B1D4C2][Open port]] ~112~ on the ADDE VM via OpenStack.

** docker-compose.yml
   :PROPERTIES:
   :CUSTOM_ID: h-E8896F4D
   :END:

Based on the directory set we have defined, the =docker-compose.yml= file that looks like:

#+INCLUDE: "../../../vms/mcidas/docker-compose.yml" src yaml


Note the ~unidata/mcidas~ container is closed source so is unavailable at DockerHub. Contact Unidata for more information.

** Start ADDE
   :PROPERTIES:
   :CUSTOM_ID: h-CD5F66AF
   :END:

Once you have done the work of setting up ADDE related directories in the way you like,

#+BEGIN_SRC shell
  docker-compose up -d
#+END_SRC

to start ADDE.

** Access ADDE from the IDV
   :PROPERTIES:
   :CUSTOM_ID: h-F5719715
   :END:

To verify all is in order, access this ADDE server from the Unidata IDV by pointing to the =adde.scigw.unidata.ucar.edu= server in the Image Data Chooser.
