gateway:
  # Path prefix to serve dask-gateway api requests under
  # This prefix will be added to all routes the gateway manages
  # in the traefik proxy.
  prefix: "/services/dask-gateway"

  # Number of instances of the gateway-server to run
  replicas: 1

  auth:
    # The auth type to use. One of {simple, kerberos, jupyterhub, custom}.
    type: jupyterhub

    jupyterhub:
      apiToken: "xxx"

  extraConfig:
    # Note that the key name here doesn't matter. Values in the
    # `extraConfig` map are concatenated, sorted by key name.
    clusteroptions: |
        from dask_gateway_server.options import Options, Integer, Float, String

        def option_handler(options):
            return {
                "worker_cores": options.worker_cores,
                "worker_memory": "%fG" % options.worker_memory,
                "image": options.image,
            }

        c.Backend.cluster_options = Options(
            Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
            String("image", default="unidata/dask-gateway:2023.9.0c", label="Image"),
            handler=option_handler,
        )


rbac:
  # Whether to enable RBAC.
  enabled: true
