name: sau-fall-2023
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - python=3
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - scikit-learn
  - scipy
