name: mvu25s
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # Standard packages
  - numpy
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas
  - pip
  - xarray
  - ipywidgets
  - python-awips
  - scikit-learn
  - seaborn
  # User requested packages
  - scipy
  - wrf-python
  - netcdf4
  - pyorbital
  - pytz
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - palmerpenguins
variables:
  ARTS_DATA_PATH: /share/ESCI345/arts-data/
