name: mvu25s
channels:
  - rttools
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - scipy
  - metpy
  - xarray
  - scikit-learn
  - cartopy
  - seaborn
  - netcdf4
  - pyorbital
  - pytz
  - siphon
  - statsmodels
  - pip
  - cfgrib
  - setuptools
  - climlab
  - climlab-rrtmg
  - typhon
  - ipympl
  - pint-xarray
  - pyarts
  - ipython=8
  - nb_conda_kernels
  - ipykernel
  - xwrf
  - pip:
    - miepython
    - git+https://github.com/proplot-dev/proplot.git@refs/pull/459/head
variables:
  ARTS_DATA_PATH: /share/ESCI345/arts-data/arts-cat-data-2.6.12/
  ARTS_XML_ATMO: /home/jovyan/esci345/atmospheres/
