name: mvu25s
channels:
  - rttools
  - conda-forge
  - defaults
dependencies:
  - python<3.12
  - numpy
  - matplotlib
  - pandas
  - scipy
  - metpy
  - xarray
  - scikit-learn
  - cartopy
  - seaborn
  - netcdf4
  - pyorbital
  - pytz
  - siphon
  - statsmodels
  - pip
  - cfgrib
  - climlab
  - climlab-rrtmg
  - typhon
  - ipympl
  - pint-xarray
  - pyarts
  - nb_conda_kernels
  - ipykernel
  - pip:
    - miepython
    - wrf-python
    - git+https://github.com/lukelbd/proplot
variables:
  ARTS_DATA_PATH: /share/ESCI345/arts-data/arts-cat-data-2.6.12/
  ARTS_XML_ATMO: /share/ESCI345/arts-data/arts-xml-data-2.6.12/
